
import type { ClinicalTrialPaper } from './types';

export const initialPapers: ClinicalTrialPaper[] = [
  {
    id: '1',
    sourceUrl: 'https://clinicaltrials.gov/ct2/show/NCT04368728',
    title: 'A Study of a New Drug for Alzheimer\'s Disease',
    principalInvestigator: 'Dr. Evelyn Reed',
    publishedDate: 'Jan 15, 2024',
    summary: 'This is a Phase 3, multicenter, randomized, double-blind, placebo-controlled study to evaluate the efficacy and safety of a new investigational drug in subjects with mild cognitive impairment due to Alzheimer\'s disease. The study will assess changes in cognitive function and daily activities over a period of 18 months.',
    imageUrl: 'https://picsum.photos/seed/aibrain/1024/768',
    imageHint: 'AI brain',
    status: 'Recruiting',
    phase: 'Phase 3',
    sponsor: 'NeuroInnovate Therapeutics',
  },
  {
    id: '2',
    sourceUrl: 'https://clinicaltrials.gov/ct2/show/NCT04508980',
    title: 'Cardiovascular Outcomes Trial for a New Diabetes Medication',
    author: 'Dr. Maria Garcia',
    publishedDate: 'Feb 20, 2024',
    summary: 'A randomized, double-blind, placebo-controlled, multicenter trial to determine the effect of a new diabetes drug on major adverse cardiovascular events (MACE) in adults with type 2 diabetes and established cardiovascular disease. Participants will be followed for up to 5 years.',
    imageUrl: 'https://picsum.photos/seed/naturepath/1024/768',
    imageHint: 'nature path',
    status: 'Completed',
    phase: 'Phase 4',
    sponsor: 'CardioHealth Inc.',
  },
  {
    id: '3',
    sourceUrl: 'https://clinicaltrials.gov/ct2/show/NCT05123456',
    title: 'A Phase 1/2 Study of a CAR-T Cell Therapy for Non-Hodgkin Lymphoma',
    principalInvestigator: 'Dr. David Chen',
    publishedDate: 'Mar 10, 2024',
    summary: 'This is a Phase 1/2 open-label study to determine the safety and efficacy of a novel CAR-T cell therapy in patients with relapsed or refractory Non-Hodgkin Lymphoma. The Phase 1 portion will focus on dose-escalation, while Phase 2 will assess the overall response rate.',
    imageUrl: 'https://picsum.photos/seed/designdesk/1024/768',
    imageHint: 'design desk',
    status: 'Recruiting',
    phase: 'Phase 1',
    sponsor: 'OncoVex Advanced Therapies',
  },
  {
    id: '4',
    sourceUrl: 'https://clinicaltrials.gov/ct2/show/NCT03898888',
    title: 'Efficacy of a Novel Vaccine for Respiratory Syncytial Virus (RSV)',
    principalInvestigator: 'Dr. Alex Grant',
    publishedDate: 'Apr 05, 2024',
    summary: 'A Phase 3, randomized, observer-blind, placebo-controlled trial to assess the efficacy, safety, and immunogenicity of an RSV vaccine in older adults. The primary endpoint is the prevention of lower respiratory tract disease caused by RSV.',
    imageUrl: 'https://picsum.photos/seed/techabs/1024/768',
    imageHint: 'technology abstract',
    status: 'Completed',
    phase: 'Phase 3',
    sponsor: 'VaxGen Global',
  },
  {
    id: '5',
    sourceUrl: 'https://clinicaltrials.gov/ct2/show/NCT05551234',
    title: 'Trial of a New Topical Treatment for Atopic Dermatitis (Eczema)',
    principalInvestigator: 'Dr. Kenji Tanaka',
    publishedDate: 'May 01, 2024',
    summary: 'A 12-week, Phase 2, randomized, double-blind, vehicle-controlled study to evaluate the efficacy, safety, and tolerability of a new topical cream for the treatment of moderate to severe atopic dermatitis in adults and adolescents. Improvement in skin lesions and itch will be measured.',
    imageUrl: 'https://picsum.photos/seed/bizmeet/1024/768',
    imageHint: 'business meeting',
    status: 'Terminated',
    phase: 'Phase 2',
    sponsor: 'Dermacure Solutions',
  },
];
