
import type { FeedItem } from './types';

export const initialFeedItems: FeedItem[] = [
  {
    id: '1',
    type: 'paper',
    sourceUrl: 'https://www.lilly.com/news/press-releases/lillys-tirzepatide-delivered-up-to-22-5-percent-weight-loss-in-adults-with-obesity-or-overweight-in-surmount-1',
    title: 'SURMOUNT-1: Tirzepatide Once Weekly for the Treatment of Obesity',
    principalInvestigator: 'Ania M. Jastreboff, MD, PhD',
    publishedDate: 'Jun 04, 2022',
    summary: 'This Phase 3, multicenter, randomized, double-blind, placebo-controlled study evaluated the efficacy and safety of Tirzepatide once weekly in adults with obesity or overweight with at least one weight-related comorbidity, without diabetes. The primary objective was to demonstrate the superiority of Tirzepatide over placebo in mean percent change in body weight.',
    imageUrl: 'https://picsum.photos/seed/aibrain/1024/768',
    imageHint: 'AI brain',
    status: 'Completed',
    phase: 'Phase 3',
    sponsor: 'Eli Lilly and Company',
  },
  {
    id: 'vid-1',
    type: 'video',
    paperId: '1',
    sourceUrl: 'https://www.lilly.com/news/press-releases/lillys-tirzepatide-delivered-up-to-22-5-percent-weight-loss-in-adults-with-obesity-or-overweight-in-surmount-1',
    title: 'Video Summary: Mounjaro for Weight Loss (SURMOUNT-1)',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/videoplay/1024/768',
    imageHint: 'video play button',
    summary: 'A quick video explaining the groundbreaking results of the SURMOUNT-1 trial for Tirzepatide (Mounjaro) in treating obesity.',
  },
  {
    id: '2',
    type: 'paper',
    sourceUrl: 'https://clinicaltrials.gov/ct2/show/NCT04508980',
    title: 'Cardiovascular Outcomes Trial for a New Diabetes Medication',
    principalInvestigator: 'Dr. Maria Garcia',
    publishedDate: 'Feb 20, 2024',
    summary: 'A randomized, double-blind, placebo-controlled, multicenter trial to determine the effect of a new diabetes drug on major adverse cardiovascular events (MACE) in adults with type 2 diabetes and established cardiovascular disease. Participants will be followed for up to 5 years.',
    imageUrl: 'https://picsum.photos/seed/naturepath/1024/768',
    imageHint: 'nature path',
    status: 'Completed',
    phase: 'Phase 4',
    sponsor: 'CardioHealth Inc.',
  },
  {
    id: '3',
    type: 'paper',
    sourceUrl: 'https://clinicaltrials.gov/ct2/show/NCT05123456',
    title: 'A Phase 1/2 Study of a CAR-T Cell Therapy for Non-Hodgkin Lymphoma',
    principalInvestigator: 'Dr. David Chen',
    publishedDate: 'Mar 10, 2024',
    summary: 'This is a Phase 1/2 open-label study to determine the safety and efficacy of a novel CAR-T cell therapy in patients with relapsed or refractory Non-Hodgkin Lymphoma. The Phase 1 portion will focus on dose-escalation, while Phase 2 will assess the overall response rate.',
    imageUrl: 'https://picsum.photos/seed/designdesk/1024/768',
    imageHint: 'design desk',
    status: 'Recruiting',
    phase: 'Phase 1',
    sponsor: 'OncoVex Advanced Therapies',
  },
    {
    id: 'vid-2',
    type: 'video',
    paperId: '3',
    sourceUrl: 'https://clinicaltrials.gov/ct2/show/NCT05123456',
    title: 'Explainer: CAR-T Cell Therapy',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/sciencevid/1024/768',
    imageHint: 'science video',
    summary: 'Learn how CAR-T cell therapy works to fight cancer like Non-Hodgkin Lymphoma in this short animated video.',
  },
  {
    id: '4',
    type: 'paper',
    sourceUrl: 'https://clinicaltrials.gov/ct2/show/NCT03898888',
    title: 'Efficacy of a Novel Vaccine for Respiratory Syncytial Virus (RSV)',
    principalInvestigator: 'Dr. Alex Grant',
    publishedDate: 'Apr 05, 2024',
    summary: 'A Phase 3, randomized, observer-blind, placebo-controlled trial to assess the efficacy, safety, and immunogenicity of an RSV vaccine in older adults. The primary endpoint is the prevention of lower respiratory tract disease caused by RSV.',
    imageUrl: 'https://picsum.photos/seed/techabs/1024/768',
    imageHint: 'technology abstract',
    status: 'Completed',
    phase: 'Phase 3',
    sponsor: 'VaxGen Global',
  },
  {
    id: '5',
    type: 'paper',
    sourceUrl: 'https://clinicaltrials.gov/ct2/show/NCT05551234',
    title: 'Trial of a New Topical Treatment for Atopic Dermatitis (Eczema)',
    principalInvestigator: 'Dr. Kenji Tanaka',
    publishedDate: 'May 01, 2024',
    summary: 'A 12-week, Phase 2, randomized, double-blind, vehicle-controlled study to evaluate the efficacy, safety, and tolerability of a new topical cream for the treatment of moderate to severe atopic dermatitis in adults and adolescents. Improvement in skin lesions and itch will be measured.',
    imageUrl: 'https://picsum.photos/seed/bizmeet/1024/768',
    imageHint: 'business meeting',
    status: 'Terminated',
    phase: 'Phase 2',
    sponsor: 'Dermacure Solutions',
  },
];
